name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: n4okins
          template: classic
          base: header, metadata

          config_timezone: Asia/Tokyo

          plugin_introduction: yes
          plugin_achievements: yes


          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_ignored: HTML,CSS,SCSS,Shell,Makefile,INI,JSON,YAML,Markdown,Jupyter
          plugin_languages_skipped: Markdown
          plugin_languages_other: yes
          plugin_languages_sections: recently-used

          plugin_habits: yes
          plugin_habits_duration: 14
          plugin_gists: yes

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
