name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: n4okins
          template: repository
          base: header,activity,community,repositories,metadata

          config_timezone: Asia/Tokyo

          plugin_introduction: yes
          plugin_achievements: yes
          plugin_lines: yes
          plugin_lines_sections: base,repositories,history
          plugin_lines_skipped: obsidian,.config,n4okins.github.io
          plugin_lines_repositories_limit: 10
          plugin_lines_history_limit: 1


          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_duration: 14
          plugin_gists: yes

          plugin_leetcode: no
          plugin_leetcode_sections: solved, skills, recent
