name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: n4okins
          template: classic
          base: header,activity,community,repositories,metadata

          config_timezone: Asia/Tokyo

          plugin_introduction: yes
          plugin_achievements: yes
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1

          plugin_languages: yes
          plugin_languages_ignored: |
            HTML,CSS,JavaScript,SCSS,TypeScript,Vue,JSON,Markdown,XML,YAML,Jupyter Notebook,Shell

          plugin_languages_skipped: Markdown
          plugin_languages_other: yes
          plugin_languages_recent_days: 365
          plugin_languages_sections: recently-used
          plugin_languages_categories: data,markup,programming,prose
          plugin_languages_recent_categories: data,markup,programming,prose
          plugin_languages_details: bytes-size, percentage, lines

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_duration: 14
          plugin_gists: yes

          plugin_leetcode: no
          plugin_leetcode_sections: solved, skills, recent
